before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
branches:
  only:
  - master
install:
- yarn
language: node_js
node_js:
- '8'
script: yarn build
after_success: node scripts/deploy.js --user $FTP_USER --password $FTP_PASSWORD
env:
  global:
  - secure: KHqmIfXsTk9vtpvuZ2dE7bgqQwz2QGFdYGUHBs8dw0rqEhfxQJyYbJG/YJ+6ytt9hXz2VJljxxfXZkJHl0UHcpNRfwHU4NMp0oWnqu5BlsO1ruluik4Yy7AdgUPGDFNgoCYdX7MB6QXD8mXzObIx3QpyVjwcXz51+SRVT8QV1+8bATEs1RJJ33gZGGSYCyh2gujKx8i2DWk2EybSNDiDTasSjGfQyzbOPL/hehpYFO/re2Pj5BcPTH/DtxL3zVzQGGLmiau2q3c32Yru8ob+sxUJ8rWBnIE6w8TzY5T0zn1hcStfSydJlkLOeC2yBgUTFJKVz6msRu33uHoTPURIG1TX3U22vueYWtL8RCnI/F342iG6nJ+LMkHzbQUrtKJ9azOXBR2KTyMbjz94FfnjjHPHLYlW+kSA/TapxIjqHHYyekeUBLsrLRmlZZ/27yT4v98DTJzUL2tqDfGG7GgD00aAlGeqvKWuir6JpH0XTFSkM19U23MNP6agGvkONDnQ4j+HwFc8vTQ1Thu3MgDVST1uKD/yFMn6OzNGmSZBD7GZIeaQ34hbrxaXSUleCij1gKNsHCvLCuGQLHA6VcFySNDEQRr1sBYfYOP3RM/Rn5jxuPI/dNgtFRwhB8udXDGyYmPT/EwTC+ZG0GEyFwrjn3FLhZYzXjkLV4+IxOavd7o=
  - secure: l4YzgKd48f1QS93mMEggEHJggrSwtS1W72Avcj3BYUyeLcDTEZmBN7uTnUnsc0rC3xMexVuN0utpwWVnSjUASrgU2yTeSW8nHk1R/b1h0SPU/sfZaCu9S9dWFZ+m1LrmaiBxBmhynfZMztbZ2e4iP4lZfWk6+CZ75NTeihLY/HocNfYqtvA3OOtYAOQyqJ/W4gvphV0i6l6SW2u0iLqn7iouE5dB5TV9acy9XAATOkSPrKDJJTn0gki2o77wnjW9qv4hwCN9+cdGPFvDS5PpgceWBUsxsBuiBv1WdN9rvKVelSh5qqg6jrbvQwiuIHoEsjZm9kmbfI6Wa8qbeQ8Feo4zvQDM12pvXzHw/wbn955xU205EDPve9NUC2/++03zt2QBTIwFW7sU+OHr8nMNN8yCMA541IQRFMx+IqE4cra3wv37g05jfvR7IaT0izsS1tCgWRTSuBzUHVvVmYoo/cABywy/qWIniKCGf9llS8D4nD3tk+t0NXV3AJy3VOTkoMFfe2FQcG5ZuecuQJffQ5GFysd/NIwTF6Xptlk/plWx8YQNhQxSWaltmllZEhGZ06UodV53ibv0JBF6/7uwRZ/Gru53kgTRN+wJoSMq7u38htOdxcUClzDmqTs+E+cwuymqfiz9k2QGicKqb1NFQDY2KsFr+RbFJq1J43p+t5M=
