before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
branches:
  only:
  - master
install:
- yarn
language: node_js
node_js:
- '8'
script: yarn build
deploy:
  provider: script
  on:
    branch: master
  skip_cleanup: true
  script: scripts/deploy.sh
